### ISSUE TITLE
Include density dependence

### ISSUE THREAD

**Issue by richardsouthwell** [gustavdelius/mizer#36]
As a subtask to #19 we want to include the density dependence (ddd & chi) and the params@lambda slots, etc. I created a new branch called density_dev, and then I used winmerge to copy the relevant parts from chi_den_sol2, then I ran  stable_community.R to check.

**Comment by gustavdelius** [comment]
Let's have a little pause while pondering the best way to set ddd. We are tempted to set it to initial_n but have to be careful with possible zeros.

**Comment by richardsouthwell** [comment]
How about the following code for setting ddd

ddd <- initial_n^(chi)
ddd[ddd==0] <- 1

**Comment by gustavdelius** [comment]
Yes, I think that should work well. initial_n should be non-zero everywhere between egg size and maturity size. Perhaps we could add a unit test that verifies that. Also it should be zero outside that range and that too could form part of the unit test. I'll add a separate issue so that you do not have to deal with unit testing at the moment.
